[package]
name = "juno-starknet-rs"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.171"
serde_json = { version = "1.0.96", features = ["raw_value"] }
cached = "0.44.0"
blockifier = {git = "https://github.com/starkware-libs/blockifier", rev = "72c7b4f4"}
starknet_api = "0.3.0"
cairo-vm = "0.8.2"
cairo-lang-casm = "2.1.0-rc1"
cairo-lang-starknet = "2.1.0-rc1"

starknet = { rev = "starknet-core/v0.5.1", git = "https://github.com/xJonathanLEI/starknet-rs" }

[lib]
crate-type = ["staticlib"]
