// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.1
// source: p2p/proto/transaction.proto

package spec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionCommon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce   *Felt252 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"` // FFU: volition will also add the selected state tree
	Version *Felt252 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *TransactionCommon) Reset() {
	*x = TransactionCommon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionCommon) ProtoMessage() {}

func (x *TransactionCommon) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionCommon.ProtoReflect.Descriptor instead.
func (*TransactionCommon) Descriptor() ([]byte, []int) {
	return file_p2p_proto_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionCommon) GetNonce() *Felt252 {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *TransactionCommon) GetVersion() *Felt252 {
	if x != nil {
		return x.Version
	}
	return nil
}

type L2TransactionCommon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender    *Address   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Signature *Signature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	MaxFee    *Felt252   `protobuf:"bytes,4,opt,name=max_fee,json=maxFee,proto3" json:"max_fee,omitempty"` // FFU: may change according to fee market spec
}

func (x *L2TransactionCommon) Reset() {
	*x = L2TransactionCommon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2TransactionCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2TransactionCommon) ProtoMessage() {}

func (x *L2TransactionCommon) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2TransactionCommon.ProtoReflect.Descriptor instead.
func (*L2TransactionCommon) Descriptor() ([]byte, []int) {
	return file_p2p_proto_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *L2TransactionCommon) GetSender() *Address {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *L2TransactionCommon) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *L2TransactionCommon) GetMaxFee() *Felt252 {
	if x != nil {
		return x.MaxFee
	}
	return nil
}

type InvokeTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Calldata []*Felt252 `protobuf:"bytes,1,rep,name=calldata,proto3" json:"calldata,omitempty"` // not streaming this, meaning limited to ~30K felts.
}

func (x *InvokeTransaction) Reset() {
	*x = InvokeTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_transaction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvokeTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeTransaction) ProtoMessage() {}

func (x *InvokeTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_transaction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeTransaction.ProtoReflect.Descriptor instead.
func (*InvokeTransaction) Descriptor() ([]byte, []int) {
	return file_p2p_proto_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeTransaction) GetCalldata() []*Felt252 {
	if x != nil {
		return x.Calldata
	}
	return nil
}

type DeclareTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassHash    *Hash `protobuf:"bytes,1,opt,name=class_hash,json=classHash,proto3" json:"class_hash,omitempty"`
	CompiledHash *Hash `protobuf:"bytes,2,opt,name=compiled_hash,json=compiledHash,proto3" json:"compiled_hash,omitempty"`
}

func (x *DeclareTransaction) Reset() {
	*x = DeclareTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_transaction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeclareTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareTransaction) ProtoMessage() {}

func (x *DeclareTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_transaction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareTransaction.ProtoReflect.Descriptor instead.
func (*DeclareTransaction) Descriptor() ([]byte, []int) {
	return file_p2p_proto_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *DeclareTransaction) GetClassHash() *Hash {
	if x != nil {
		return x.ClassHash
	}
	return nil
}

func (x *DeclareTransaction) GetCompiledHash() *Hash {
	if x != nil {
		return x.CompiledHash
	}
	return nil
}

type DeployAccountTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassHash           *Hash      `protobuf:"bytes,1,opt,name=class_hash,json=classHash,proto3" json:"class_hash,omitempty"`
	ConstructorCalldata []*Felt252 `protobuf:"bytes,2,rep,name=constructor_calldata,json=constructorCalldata,proto3" json:"constructor_calldata,omitempty"`
}

func (x *DeployAccountTransaction) Reset() {
	*x = DeployAccountTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_transaction_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployAccountTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAccountTransaction) ProtoMessage() {}

func (x *DeployAccountTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_transaction_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAccountTransaction.ProtoReflect.Descriptor instead.
func (*DeployAccountTransaction) Descriptor() ([]byte, []int) {
	return file_p2p_proto_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *DeployAccountTransaction) GetClassHash() *Hash {
	if x != nil {
		return x.ClassHash
	}
	return nil
}

func (x *DeployAccountTransaction) GetConstructorCalldata() []*Felt252 {
	if x != nil {
		return x.ConstructorCalldata
	}
	return nil
}

type L2Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *L2TransactionCommon `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	// Types that are assignable to Txn:
	//
	//	*L2Transaction_Invoke
	//	*L2Transaction_Declare
	//	*L2Transaction_DeployAccount
	Txn isL2Transaction_Txn `protobuf_oneof:"txn"`
}

func (x *L2Transaction) Reset() {
	*x = L2Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_transaction_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2Transaction) ProtoMessage() {}

func (x *L2Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_transaction_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2Transaction.ProtoReflect.Descriptor instead.
func (*L2Transaction) Descriptor() ([]byte, []int) {
	return file_p2p_proto_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *L2Transaction) GetCommon() *L2TransactionCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

func (m *L2Transaction) GetTxn() isL2Transaction_Txn {
	if m != nil {
		return m.Txn
	}
	return nil
}

func (x *L2Transaction) GetInvoke() *InvokeTransaction {
	if x, ok := x.GetTxn().(*L2Transaction_Invoke); ok {
		return x.Invoke
	}
	return nil
}

func (x *L2Transaction) GetDeclare() *DeclareTransaction {
	if x, ok := x.GetTxn().(*L2Transaction_Declare); ok {
		return x.Declare
	}
	return nil
}

func (x *L2Transaction) GetDeployAccount() *DeployAccountTransaction {
	if x, ok := x.GetTxn().(*L2Transaction_DeployAccount); ok {
		return x.DeployAccount
	}
	return nil
}

type isL2Transaction_Txn interface {
	isL2Transaction_Txn()
}

type L2Transaction_Invoke struct {
	Invoke *InvokeTransaction `protobuf:"bytes,2,opt,name=invoke,proto3,oneof"`
}

type L2Transaction_Declare struct {
	Declare *DeclareTransaction `protobuf:"bytes,3,opt,name=declare,proto3,oneof"`
}

type L2Transaction_DeployAccount struct {
	DeployAccount *DeployAccountTransaction `protobuf:"bytes,4,opt,name=deploy_account,json=deployAccount,proto3,oneof"`
}

func (*L2Transaction_Invoke) isL2Transaction_Txn() {}

func (*L2Transaction_Declare) isL2Transaction_Txn() {}

func (*L2Transaction_DeployAccount) isL2Transaction_Txn() {}

type L1HandlerTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contract           *Address   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	EntryPointSelector *Felt252   `protobuf:"bytes,2,opt,name=entry_point_selector,json=entryPointSelector,proto3" json:"entry_point_selector,omitempty"`
	Calldata           []*Felt252 `protobuf:"bytes,3,rep,name=calldata,proto3" json:"calldata,omitempty"`
}

func (x *L1HandlerTransaction) Reset() {
	*x = L1HandlerTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_transaction_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L1HandlerTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L1HandlerTransaction) ProtoMessage() {}

func (x *L1HandlerTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_transaction_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L1HandlerTransaction.ProtoReflect.Descriptor instead.
func (*L1HandlerTransaction) Descriptor() ([]byte, []int) {
	return file_p2p_proto_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *L1HandlerTransaction) GetContract() *Address {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *L1HandlerTransaction) GetEntryPointSelector() *Felt252 {
	if x != nil {
		return x.EntryPointSelector
	}
	return nil
}

func (x *L1HandlerTransaction) GetCalldata() []*Felt252 {
	if x != nil {
		return x.Calldata
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *TransactionCommon `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	// Types that are assignable to Txn:
	//
	//	*Transaction_L2Transaction
	//	*Transaction_L1Handler
	Txn isTransaction_Txn `protobuf_oneof:"txn"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_transaction_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_transaction_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_p2p_proto_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *Transaction) GetCommon() *TransactionCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

func (m *Transaction) GetTxn() isTransaction_Txn {
	if m != nil {
		return m.Txn
	}
	return nil
}

func (x *Transaction) GetL2Transaction() *L2Transaction {
	if x, ok := x.GetTxn().(*Transaction_L2Transaction); ok {
		return x.L2Transaction
	}
	return nil
}

func (x *Transaction) GetL1Handler() *L1HandlerTransaction {
	if x, ok := x.GetTxn().(*Transaction_L1Handler); ok {
		return x.L1Handler
	}
	return nil
}

type isTransaction_Txn interface {
	isTransaction_Txn()
}

type Transaction_L2Transaction struct {
	L2Transaction *L2Transaction `protobuf:"bytes,2,opt,name=l2Transaction,proto3,oneof"`
}

type Transaction_L1Handler struct {
	L1Handler *L1HandlerTransaction `protobuf:"bytes,3,opt,name=l1handler,proto3,oneof"`
}

func (*Transaction_L2Transaction) isTransaction_Txn() {}

func (*Transaction_L1Handler) isTransaction_Txn() {}

type GetTransactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *BlockID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTransactions) Reset() {
	*x = GetTransactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_transaction_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactions) ProtoMessage() {}

func (x *GetTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_transaction_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactions.ProtoReflect.Descriptor instead.
func (*GetTransactions) Descriptor() ([]byte, []int) {
	return file_p2p_proto_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *GetTransactions) GetId() *BlockID {
	if x != nil {
		return x.Id
	}
	return nil
}

// can be several in a single reply
type Transactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transactions []*Transaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
}

func (x *Transactions) Reset() {
	*x = Transactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_transaction_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transactions) ProtoMessage() {}

func (x *Transactions) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_transaction_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transactions.ProtoReflect.Descriptor instead.
func (*Transactions) Descriptor() ([]byte, []int) {
	return file_p2p_proto_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *Transactions) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_p2p_proto_transaction_proto protoreflect.FileDescriptor

var file_p2p_proto_transaction_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x32, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x70,
	0x32, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x05, 0x6e, 0x6f,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x65, 0x6c, 0x74,
	0x32, 0x35, 0x32, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x65,
	0x6c, 0x74, 0x32, 0x35, 0x32, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x84,
	0x01, 0x0a, 0x13, 0x4c, 0x32, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x21, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x66, 0x65, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x65, 0x6c, 0x74, 0x32, 0x35, 0x32, 0x52, 0x06, 0x6d,
	0x61, 0x78, 0x46, 0x65, 0x65, 0x22, 0x39, 0x0a, 0x11, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x08, 0x63, 0x61,
	0x6c, 0x6c, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46,
	0x65, 0x6c, 0x74, 0x32, 0x35, 0x32, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x66, 0x0a, 0x12, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x61, 0x73,
	0x68, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2a, 0x0a, 0x0d,
	0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x64, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70,
	0x69, 0x6c, 0x65, 0x64, 0x48, 0x61, 0x73, 0x68, 0x22, 0x7d, 0x0a, 0x18, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52,
	0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x48, 0x61, 0x73, 0x68, 0x12, 0x3b, 0x0a, 0x14, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x65, 0x6c, 0x74, 0x32,
	0x35, 0x32, 0x52, 0x13, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x43,
	0x61, 0x6c, 0x6c, 0x64, 0x61, 0x74, 0x61, 0x22, 0xe7, 0x01, 0x0a, 0x0d, 0x4c, 0x32, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x06, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4c, 0x32, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52,
	0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x06, 0x69, 0x6e, 0x76, 0x6f, 0x6b,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x69,
	0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x07, 0x64,
	0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x74, 0x78,
	0x6e, 0x22, 0x9e, 0x01, 0x0a, 0x14, 0x4c, 0x31, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x12, 0x3a, 0x0a, 0x14, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f,
	0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x46, 0x65, 0x6c, 0x74, 0x32, 0x35, 0x32, 0x52, 0x12, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x24, 0x0a, 0x08,
	0x63, 0x61, 0x6c, 0x6c, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x46, 0x65, 0x6c, 0x74, 0x32, 0x35, 0x32, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x64, 0x61,
	0x74, 0x61, 0x22, 0xaf, 0x01, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x36,
	0x0a, 0x0d, 0x6c, 0x32, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4c, 0x32, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0d, 0x6c, 0x32, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x09, 0x6c, 0x31, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4c, 0x31, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x00, 0x52, 0x09, 0x6c, 0x31, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x42, 0x05, 0x0a,
	0x03, 0x74, 0x78, 0x6e, 0x22, 0x2b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x40, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x30, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6a, 0x75, 0x6e, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x6e, 0x65, 0x74, 0x2f,
	0x70, 0x32, 0x70, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_p2p_proto_transaction_proto_rawDescOnce sync.Once
	file_p2p_proto_transaction_proto_rawDescData = file_p2p_proto_transaction_proto_rawDesc
)

func file_p2p_proto_transaction_proto_rawDescGZIP() []byte {
	file_p2p_proto_transaction_proto_rawDescOnce.Do(func() {
		file_p2p_proto_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_p2p_proto_transaction_proto_rawDescData)
	})
	return file_p2p_proto_transaction_proto_rawDescData
}

var file_p2p_proto_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_p2p_proto_transaction_proto_goTypes = []interface{}{
	(*TransactionCommon)(nil),        // 0: TransactionCommon
	(*L2TransactionCommon)(nil),      // 1: L2TransactionCommon
	(*InvokeTransaction)(nil),        // 2: InvokeTransaction
	(*DeclareTransaction)(nil),       // 3: DeclareTransaction
	(*DeployAccountTransaction)(nil), // 4: DeployAccountTransaction
	(*L2Transaction)(nil),            // 5: L2Transaction
	(*L1HandlerTransaction)(nil),     // 6: L1HandlerTransaction
	(*Transaction)(nil),              // 7: Transaction
	(*GetTransactions)(nil),          // 8: GetTransactions
	(*Transactions)(nil),             // 9: Transactions
	(*Felt252)(nil),                  // 10: Felt252
	(*Address)(nil),                  // 11: Address
	(*Signature)(nil),                // 12: Signature
	(*Hash)(nil),                     // 13: Hash
	(*BlockID)(nil),                  // 14: BlockID
}
var file_p2p_proto_transaction_proto_depIdxs = []int32{
	10, // 0: TransactionCommon.nonce:type_name -> Felt252
	10, // 1: TransactionCommon.version:type_name -> Felt252
	11, // 2: L2TransactionCommon.sender:type_name -> Address
	12, // 3: L2TransactionCommon.signature:type_name -> Signature
	10, // 4: L2TransactionCommon.max_fee:type_name -> Felt252
	10, // 5: InvokeTransaction.calldata:type_name -> Felt252
	13, // 6: DeclareTransaction.class_hash:type_name -> Hash
	13, // 7: DeclareTransaction.compiled_hash:type_name -> Hash
	13, // 8: DeployAccountTransaction.class_hash:type_name -> Hash
	10, // 9: DeployAccountTransaction.constructor_calldata:type_name -> Felt252
	1,  // 10: L2Transaction.common:type_name -> L2TransactionCommon
	2,  // 11: L2Transaction.invoke:type_name -> InvokeTransaction
	3,  // 12: L2Transaction.declare:type_name -> DeclareTransaction
	4,  // 13: L2Transaction.deploy_account:type_name -> DeployAccountTransaction
	11, // 14: L1HandlerTransaction.contract:type_name -> Address
	10, // 15: L1HandlerTransaction.entry_point_selector:type_name -> Felt252
	10, // 16: L1HandlerTransaction.calldata:type_name -> Felt252
	0,  // 17: Transaction.common:type_name -> TransactionCommon
	5,  // 18: Transaction.l2Transaction:type_name -> L2Transaction
	6,  // 19: Transaction.l1handler:type_name -> L1HandlerTransaction
	14, // 20: GetTransactions.id:type_name -> BlockID
	7,  // 21: Transactions.transactions:type_name -> Transaction
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_p2p_proto_transaction_proto_init() }
func file_p2p_proto_transaction_proto_init() {
	if File_p2p_proto_transaction_proto != nil {
		return
	}
	file_p2p_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_p2p_proto_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionCommon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2TransactionCommon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_transaction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvokeTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_transaction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeclareTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_transaction_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployAccountTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_transaction_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_transaction_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L1HandlerTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_transaction_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_transaction_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTransactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_transaction_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_p2p_proto_transaction_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*L2Transaction_Invoke)(nil),
		(*L2Transaction_Declare)(nil),
		(*L2Transaction_DeployAccount)(nil),
	}
	file_p2p_proto_transaction_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Transaction_L2Transaction)(nil),
		(*Transaction_L1Handler)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_p2p_proto_transaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p2p_proto_transaction_proto_goTypes,
		DependencyIndexes: file_p2p_proto_transaction_proto_depIdxs,
		MessageInfos:      file_p2p_proto_transaction_proto_msgTypes,
	}.Build()
	File_p2p_proto_transaction_proto = out.File
	file_p2p_proto_transaction_proto_rawDesc = nil
	file_p2p_proto_transaction_proto_goTypes = nil
	file_p2p_proto_transaction_proto_depIdxs = nil
}
