name: starknet-js tests

on:
  workflow_call:
    inputs:
      TEST_RPC_URL:
        required: true
        type: string
      TEST_ACCOUNT_ADDRESS:
        required: true
        type: string
      TEST_ACCOUNT_PRIVATE_KEY:
        required: true
        type: string

jobs:
  starknet-js-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3.5.3
      with:
        repository: starknet-io/starknet.js
        ref: v5.19.5

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      env:
        TEST_RPC_URL: ${{secrets.TEST_RPC_URL}}
        TEST_ACCOUNT_ADDRESS: ${{ secrets.TEST_ACCOUNT_ADDRESS }}
        TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_ACCOUNT_PRIVATE_KEY }}