name: starknet-js tests

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
    secrets:
      TEST_RPC_URL:
        required: false
      TEST_ACCOUNT_ADDRESS:
        required: false
      TEST_ACCOUNT_PRIVATE_KEY:
          required: false

jobs:
  starknet-js-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TEST_RPC_URL: ${{ secrets.TEST_RPC_URL }}
      TEST_ACCOUNT_ADDRESS: ${{ secrets.TEST_ACCOUNT_ADDRESS }}
      TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_ACCOUNT_PRIVATE_KEY }}
      
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          repository: starknet-io/starknet.js
          ref: v5.19.5
  
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      - name: Install dependencies
        run: npm ci
  
      - name: Run tests
        run: npm test